import type { Addon } from "./addon/config/index.ts";
import { 
    join,
    prettier
} from "./deps.ts";

const filePath = ['types', 'lost.d.ts'];

export class DeclarationsManager {
    /** Creates 'lost.d.ts' file for project */
    async create(config: Addon) {
        const addons = `"${config.info.id}"`

        const properties = `${config.properties.map(property => {
            let type: string = 'unknown';

            if (
                property.type === 'integer' ||
                property.type === 'float' ||
                property.type === 'percent'
            ) {
                type = 'number';
            }
            if (
                property.type === 'text' ||
                property.type === 'longtext'
            ) {
                return 'string';
            }
            if (property.type === 'check') type = 'boolean';
            if (property.type === 'combo') type = `{${property.allItemIds().map(id => `"${id}": unknown`)}}`;
            if (property.type === 'color') type = 'SDK.Color';
            return `"${property.id}": ${type}`
        })}`;

        const initProperties = `${config.properties.map(property => {
            if (property.type === 'combo') return `${property.id}: number`;
            return `Properties["${property.id}"]`;
        })}`

        const actions = `${config.allCategories().map(category =>
            category.allActions().map(action =>
                `"${action.method.name}"`
            )
        )}`;
        const conditions = `${config.allCategories().map(category =>
            category.allConditions().map(condition => 
                `"${condition.method.name}"`
            )
        )}`;
        const expressions = `${config.allCategories().map(category =>
            category.allExpressions().map(expression =>
                `"${expression.method.name}"`
            )
        )}`;
        await Deno.writeTextFile(join(Deno.cwd(), ...filePath), await prettier.format(`
            /**
            * @important
            * This file is auto-generated by "Lost C3 Framework".
            * Changes to this file will be overwritten after next build!
            */
            type Addons = [${addons}];
            type Properties = {${properties}};

            type InitProperties = [${initProperties}];

            type Aces = {
                actions: [${actions}];
                conditions: [${conditions}];
                expressions: [${expressions}];
            };

            type AceId<Type extends keyof Aces> = Aces[Type][number];
            type AddonId = Addons[number];
            type PropertyId = keyof Properties;
        `, { parser: 'babel-ts' }));
    }
}