import type { Addon } from "../config.ts";
import { 
    path,
    prettier
} from "../deps.ts";
import { PATHS } from "../main.ts";

export class DeclarationsSystem {
    /** Creates 'lost.d.ts' file for project */
    async createFile(config: Addon) {
        const addons = `"${config.info.id}"`

        const properties = `${config.properties.map(property => {
            let type: string = 'unknown';

            if (
                property.type === 'integer' ||
                property.type === 'float' ||
                property.type === 'percent'
            ) {
                type = 'number';
            }
            if (
                property.type === 'text' ||
                property.type === 'longtext'
            ) {
                type = 'string';
            }
            if (property.type === 'check') type = 'boolean';
            if (property.type === 'combo') type = `{${property.allItemIds().map(id => `"${id}": {}`)}}`;
            if (property.type === 'color') type = 'SDK.Color';

            return `"${property.id}": ${type}`
        })}`;

        let index = -1;
        const initProperties = `${config.properties.flatMap(property => {
            let value: string | [] = '';

            if (property.type === 'combo') {
                index++;
                value = `${property.id}: number`;
            } else if (
                property.type === 'group' ||
                property.type === 'info' ||
                property.type === 'link'
            ) {
                value = [];
            } else {
                index++;
                value = `Properties["${property.id}"]`;
            }
            
            if (!Array.isArray(value)) return `${value} /** ${index} */`;
            return value;
        })}`

        const actions = `${config.allCategories().map(category =>
            category.allActions().map(action =>
                `"${action.method.name}"`
            )
        )}`;
        const conditions = `${config.allCategories().map(category =>
            category.allConditions().map(condition => 
                `"${condition.method.name}"`
            )
        )}`;
        const expressions = `${config.allCategories().map(category =>
            category.allExpressions().map(expression =>
                `"${expression.method.name}"`
            )
        )}`;
        await Deno.writeTextFile(
            path.join(PATHS.TYPES, 'lost.d.ts'), 
            await prettier.format(`
                /**
                * @important
                * This file is auto-generated by "Lost C3 Framework".
                * Changes to this file will be overwritten after next build!
                */
                type Addons = [${addons}];
                type Properties = {${properties}};

                type InitProperties = [${initProperties}];

                type Aces = {
                    actions: [${actions}];
                    conditions: [${conditions}];
                    expressions: [${expressions}];
                };

                type AceId<Type extends keyof Aces> = Aces[Type][number];
                type AddonId = Addons[number];
                type PropertyId = keyof Properties;
            `, { parser: 'babel-ts' }
        ));
    }
}